[project]
name = "classiceyes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "networkx>=3.5",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "recordlinkage>=0.16",
]
